services:
    inn_kpp_entity_validator:
        class: LaxCorp\InnKppBundle\Validator\Constraints\InnKppEntityValidator
        public: true
        arguments: [ "@doctrine" ]
        tags:
            - { name: validator.constraint_validator, alias: inn_kpp_entity_validator }